lemma_fixes:
  миш: миша
  люди: люди
  люда: люди
  кота: кіт
  кот: кіт
  вбивці: вбивця
word_replacements:
  заяць: заєць
word_blacklist:
- шати
- бути
- стати
- могти
distractors:
  NAMED_ENTITY:
    animal:
      male:
      - їжак
      - ведмідь
      - півень
      - жираф
      - слон
      female:
      - коза
      - жаба
      - свиня
      - мавпа
      - зозуля
      neutral:
      - котеня
      - слоненя
      - зайченя
      - жабеня
      - козеня
      - мавпеня
      - тигреня
      - козеня
      - вовчисько
    human:
      male:
      - син
      - багатир
      - Петро
      - лісник
      - селянин
      - чорт
      - домовик
      neutral:
      - дівча
      - дитя
      - немовля
      female:
      - селянка
      - відьма
      - жінка
      - дочка
      - сестра
      - мати
      - королева
  COMMON_NOUN:
    male:
    - автомобіль
    - будинок
    - шлях
    - ящик
    - меч
    - замок
    - стіл
    neutral:
    - дерево
    - яйце
    - ім'я
    - яблуко
    - місто
    - озеро
    - поле
    - вікно
    - ліжко
    - листя
    - шиття
    - мистецтво
    female:
    - гривня
    - природа
    - трава
    - річка
    - книга
    - дорога
    - кімната
